service: aws-python-flask-api-project

frameworkVersion: '2'

custom:
  wsgi:
    app: app.app

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: '20201221'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:*
        - apigateway:*
        - cloudformation:*
        - dynamodb:*
      Resource: '*'

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

resources:
  Resources:
    admissionsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: NewAdmissions-${env:STAGE}
        AttributeDefinitions:
          - AttributeName: institute
            AttributeType: S
          - AttributeName: enrollment
            AttributeType: S
        KeySchema:
          - AttributeName: institute
            KeyType: HASH
          - AttributeName: enrollment
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-wsgi
  - serverless-python-requirements
